### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by Ruin0x11** [Ruin0x11/intellij-lsp-server#30]
It would be very valuable to add Kotlin support, since all first-class Kotlin language support is currently contained within IDEs like IntelliJ. However, this is somewhat trickier than working on Java language features since
- Kotlin uses tons of type inference, meaning a Kotlin PSI document might not have enough information on types, etc. without doing extra resolution
- IntelliJ doesn't include docs or sources for its Kotlin plugin as part of the plugin SDK. They are available as part of the Kotlin repo, just not in the gradle-provided sources. This makes trying to debug and step into the Kotlin plugin code to get a feel for its behavior quite frustrating, and it isn't always clear why certain IDE features break when called from the LSP server.

But it would definitely be worth the challenge, to have a decent support for Kotlin code awareness outside an IDE for the first time. It would also allow self-hosting the development of the LSP plugin, to further guarantee its stability for more obscure use cases.

**Comment by Ruin0x11** [comment]
Preliminary support added in #31.

**Comment by jojojames** [comment]
Getting these traces with failing completion in a Kotlin project.

```
> Task :runIde 
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
Apr 18, 2018 1:41:36 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.RuntimeException: java.lang.AssertionError: Assertion failed
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.AssertionError: Assertion failed
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: java.lang.AssertionError: Assertion failed
        at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:179)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:651)
        at com.ruin.lsp.util.IntellijUtilKt.invokeAndWaitIfNeeded(IntellijUtil.kt:58)
        at com.ruin.lsp.model.MyLanguageServerKt.executeAndGetResult(MyLanguageServer.kt:148)
        at com.ruin.lsp.model.MyLanguageServerKt.access$executeAndGetResult(MyLanguageServer.kt:1)
        at com.ruin.lsp.model.MyLanguageServerKt$asCancellableInvokeAndWaitFuture$1.apply(MyLanguageServer.kt:136)
        at com.ruin.lsp.model.MyLanguageServerKt$asCancellableInvokeAndWaitFuture$1.apply(MyLanguageServer.kt)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 6 more
Caused by: java.lang.AssertionError: Assertion failed
        at org.jetbrains.kotlin.idea.completion.ToFromOriginalFileMapper.<init>(ToFromOriginalFileMapper.kt:48)
        at org.jetbrains.kotlin.idea.completion.ToFromOriginalFileMapper.<init>(ToFromOriginalFileMapper.kt:25)
        at org.jetbrains.kotlin.idea.completion.ToFromOriginalFileMapper$Companion.create(ToFromOriginalFileMapper.kt:34)
        at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.performCompletion(KotlinCompletionContributor.kt:239)
        at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.access$performCompletion(KotlinCompletionContributor.kt:48)
        at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor$provider$1.addCompletions(KotlinCompletionContributor.kt:59)
        at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
        at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:143)
        at com.ruin.lsp.commands.document.completion.CompletionCommandKt.getVariantsFromContributors(CompletionCommand.kt:95)
        at com.ruin.lsp.commands.document.completion.CompletionResultSetImpl.runRemainingContributors(CompletionResultSetImpl.kt:89)
        at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
        at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
        at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
        at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:143)
        at com.ruin.lsp.commands.document.completion.CompletionCommandKt.getVariantsFromContributors(CompletionCommand.kt:95)
        at com.ruin.lsp.commands.document.completion.CompletionCommandKt.performCompletion(CompletionCommand.kt:73)
        at com.ruin.lsp.commands.document.completion.CompletionCommand$execute$1.invoke(CompletionCommand.kt:37)
        at com.ruin.lsp.commands.document.completion.CompletionCommand$execute$1.invoke(CompletionCommand.kt:22)
        at com.ruin.lsp.util.EditorUtilKt.withEditor(EditorUtil.kt:47)
        at com.ruin.lsp.commands.document.completion.CompletionCommand.execute(CompletionCommand.kt:31)
        at com.ruin.lsp.commands.document.completion.CompletionCommand.execute(CompletionCommand.kt:22)
        at com.ruin.lsp.model.MyLanguageServerKt$executeAndGetResult$1.compute(MyLanguageServer.kt:153)
        at com.ruin.lsp.util.IntellijUtilKt$invokeAndWaitIfNeeded$1.run(IntellijUtil.kt:58)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
        at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Some completion seems to be working but 'dot' syntax seems to fail (though that's not the only time this fails.)

Once I find some more time, I'll see if I can cook up a small project to reproduce the issue. I'll leave this here in case you already understand what's going on.

Thanks!

**Comment by Ruin0x11** [comment]
Sure, that would be appreciated.

**Comment by Ruin0x11** [comment]
I found the issue and opened #36 tracking it.
