### ISSUE TITLE
Android Studio support

### ISSUE THREAD

**Issue by jojojames** [Ruin0x11/intellij-lsp-server#32]
Hi!

I tried installing the plugin in Android Studio and it looks like Android Studio has a build version too low for the server.

I think Android Studio 3.2 (beta) is at build 173 whereas the minimum for lsp-server is at 181.

I played around with changing the minimum version in plugin.xml to 173 but then it stops on 

   org.jetbrains.idea.maven being a missing dependency.

Not sure how feasible it would be to support Android Studio but I'd thought I'd bring it up.

**Comment by Ruin0x11** [comment]
Hmm, didn't realize that a version upgrade would bring that incompatibility. I'll see if I can return it to 173.

**Comment by jojojames** [comment]
Sounds good, this is what I get in Android Studio 3.2 beta.

```
Plugin 'com.ruin.lsp' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.NoClassDefFoundError: org/eclipse/lsp4j/services/LanguageServer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:279)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:275)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:244)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:142)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:74)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:61)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.ruin.lsp.model.LanguageServerService.<init>(LanguageServerRunner.kt:98)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:474)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.eclipse.lsp4j.services.LanguageServer PluginClassLoader[com.ruin.lsp, 0.1] com.intellij.ide.plugins.cl.PluginClassLoader@102aa8ca
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 48 more
```

This is the jar I'm using.

```
libs/ $ pwd
/Users/james/.emacs.d/fork/intellij-lsp-server/build/libs
libs/ $ ls
intellij-lsp-server-0.1.jar
libs/ $ 
```

**Comment by Ruin0x11** [comment]
I haven't actually made a release in a while, should get around to it. The lastest code on master shouldn't have issues.

**Comment by jojojames** [comment]
This is the commit I'm using.

https://github.com/Ruin0x11/intellij-lsp-server/commit/57965e3909a1905d6f4837f8b55fd2c350fd7f99

**Comment by Ruin0x11** [comment]
Can't seem to reproduce on my end, although I run Windows. Which OS are you using?

**Comment by jojojames** [comment]
OSX

**Comment by Ruin0x11** [comment]
I got the latest master working on my macOS machine. Could you see if it works for you?

**Comment by jojojames** [comment]
I'll give it a shot and update this thread.
