### ISSUE TITLE
AssertionError when completing Kotlin

### ISSUE THREAD

**Issue by Ruin0x11** [Ruin0x11/intellij-lsp-server#36]
After creating a new Kotlin project and trying to edit text inside a function call, this error occurs.

```
Apr 20, 2018 12:30:50 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.RuntimeException: java.lang.AssertionError: Assertion failed
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.AssertionError: Assertion failed
<...>
Caused by: java.lang.AssertionError: Assertion failed
	at org.jetbrains.kotlin.idea.completion.ToFromOriginalFileMapper.<init>(ToFromOriginalFileMapper.kt:48)
	at org.jetbrains.kotlin.idea.completion.ToFromOriginalFileMapper.<init>(ToFromOriginalFileMapper.kt:25)
	at org.jetbrains.kotlin.idea.completion.ToFromOriginalFileMapper$Companion.create(ToFromOriginalFileMapper.kt:34)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.performCompletion(KotlinCompletionContributor.kt:235)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.access$performCompletion(KotlinCompletionContributor.kt:47)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor$provider$1.addCompletions(KotlinCompletionContributor.kt:58)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:152)
	at com.ruin.lsp.commands.document.completion.CompletionCommandKt.getVariantsFromContributors(CompletionCommand.kt:102)
	at com.ruin.lsp.commands.document.completion.CompletionResultSetImpl.runRemainingContributors(CompletionResultSetImpl.kt:89)
<...>
```

It can be reproduced by creating a file with this code and typing some string literals:

```kotlin
fun main(args: Array<String>) {
    arrayOf(/*caret*/)
}
```

This error only happens when editing Kotlin. The main cause seems to be two references to `PsiFile`s in `CompletionParameters` having different lengths. It may be an issue of when the file referenced in the document is copied to insert the dummy identifier for completion purposes.

**Comment by jojojames** [comment]
Looks good, I don't see this anymore from brief testing.
